In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import random
import os
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import cv2
import os
import tensorflow as tf
import keras.backend as K
from keras.applications import Xception
from keras.layers import UpSampling2D, Conv2D, Activation, LeakyReLU, BatchNormalization
from keras import Model
from keras.losses import binary_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tqdm import tqdm_notebook

Using TensorFlow backend.


### The Data

In [2]:
df_train = pd.read_csv('./input/severstal-steel-defect-detection/train.csv')

In [3]:
df_train.shape

(50272, 2)

In [4]:
df_train.head()

ImageId_ClassId                                      EncodedPixels
0  0002cc93b.jpg_1  29102 12 29346 24 29602 24 29858 24 30114 24 3...
1  0002cc93b.jpg_2                                                NaN
2  0002cc93b.jpg_3                                                NaN
3  0002cc93b.jpg_4                                                NaN
4  00031f466.jpg_1                                                NaN

In [6]:
df_train['Defect'] = df_train['EncodedPixels'].notnull()
df_train['ClassId'] = df_train['ImageId_ClassId'].str[-1:]
df_train['ImageId'] = df_train['ImageId_ClassId'].str[:-2]

In [7]:
df_train.shape

(50272, 5)

In [8]:
df_train.head()

ImageId_ClassId                                      EncodedPixels  Defect  \
0  0002cc93b.jpg_1  29102 12 29346 24 29602 24 29858 24 30114 24 3...    True   
1  0002cc93b.jpg_2                                                NaN   False   
2  0002cc93b.jpg_3                                                NaN   False   
3  0002cc93b.jpg_4                                                NaN   False   
4  00031f466.jpg_1                                                NaN   False   

  ClassId        ImageId  
0       1  0002cc93b.jpg  
1       2  0002cc93b.jpg  
2       3  0002cc93b.jpg  
3       4  0002cc93b.jpg  
4       1  00031f466.jpg

In [9]:
df_train = df_train[['ImageId','ClassId','Defect','EncodedPixels']]

In [10]:
df_train.shape

(50272, 4)

In [11]:
df_train.head()

ImageId ClassId  Defect  \
0  0002cc93b.jpg       1    True   
1  0002cc93b.jpg       2   False   
2  0002cc93b.jpg       3   False   
3  0002cc93b.jpg       4   False   
4  00031f466.jpg       1   False   

                                       EncodedPixels  
0  29102 12 29346 24 29602 24 29858 24 30114 24 3...  
1                                                NaN  
2                                                NaN  
3                                                NaN  
4                                                NaN

In [14]:
df_train = df_train[df_train.Defect]

In [15]:
df_train.shape

(7095, 4)

In [16]:
df_train.head()

ImageId ClassId  Defect  \
0   0002cc93b.jpg       1    True   
18  0007a71bf.jpg       3    True   
20  000a4bcdd.jpg       1    True   
27  000f6bf48.jpg       4    True   
30  0014fce06.jpg       3    True   

                                        EncodedPixels  
0   29102 12 29346 24 29602 24 29858 24 30114 24 3...  
18  18661 28 18863 82 19091 110 19347 110 19603 11...  
20  37607 3 37858 8 38108 14 38359 20 38610 25 388...  
27  131973 1 132228 4 132483 6 132738 8 132993 11 ...  
30  229501 11 229741 33 229981 55 230221 77 230468...

In [17]:
df_train = df_train.drop(['Defect'], axis=1)

In [18]:
df_train.head()

ImageId ClassId                                      EncodedPixels
0   0002cc93b.jpg       1  29102 12 29346 24 29602 24 29858 24 30114 24 3...
18  0007a71bf.jpg       3  18661 28 18863 82 19091 110 19347 110 19603 11...
20  000a4bcdd.jpg       1  37607 3 37858 8 38108 14 38359 20 38610 25 388...
27  000f6bf48.jpg       4  131973 1 132228 4 132483 6 132738 8 132993 11 ...
30  0014fce06.jpg       3  229501 11 229741 33 229981 55 230221 77 230468...

### Utility functions

In [19]:
# This function uses a 0 based start index (arrays, matrixes and imgs start a index 0)
def mask2rle(img):
    tmp = np.rot90( np.flipud( img ), k=3 )
    rle = []
    lastColor = 0;
    startpos = 0
    endpos = 0

    tmp = tmp.reshape(-1,1)   
    for i in range( len(tmp) ):
        if (lastColor==0) and tmp[i]>0:
            startpos = i
            lastColor = 1
        elif (lastColor==1)and(tmp[i]==0):
            endpos = i-1
            lastColor = 0
            rle.append( str(startpos)+' '+str(endpos-startpos+1) )
    return " ".join(rle)

In [20]:
img = [
    [0, 1, 0, 0, 0],
    [0, 1, 1, 1, 0], 
    [0, 1, 0, 1, 0],
    [0, 1, 1, 1, 0], 
    [0, 0, 0, 1, 0],
]

res = mask2rle(img)
print(res)

5 4 11 1 13 1 16 4


In [21]:
# This function uses a 0 based start index (arrays, matrixes and imgs start a index 0)
def rle2mask(rle, imgshape):
    width = imgshape[0]
    height= imgshape[1]
    
    mask= np.zeros( width*height ).astype(np.uint8)
    
    array = np.asarray([int(x) for x in rle.split()])
    starts = array[0::2]
    lengths = array[1::2]

    current_position = 0
    for index, start in enumerate(starts):
        mask[int(start):int(start+lengths[index])] = 1
        current_position += lengths[index]
        
    return np.flipud( np.rot90( mask.reshape(height, width), k=1 ) )

In [22]:
res = rle2mask("5 4 11 1 13 1 16 4", (5, 5))
print(res)

[[0 1 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 1 0]]


### Xception Model in Keras

In [25]:
ORIG_IMG_SIZE_HEIGHT = 256
ORIG_IMG_SIZE_WIDTH = 1600
TRAIN_IMG_SIZE_HEIGHT = 128
TRAIN_IMG_SIZE_WIDTH = 800

BATCH_SIZE = 2
EPOCHS = 3
PATIENCE = 3

In [28]:
def keras_generator(batch_size):
    while True:
        x_batch = []
        y_batch = []
        
        for i in range(batch_size):            
            fn = df_train['ImageId'].iloc[i]
            img = cv2.imread( './input/severstal-steel-defect-detection/train_images/'+fn )
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)            
            
            mask = rle2mask(df_train['EncodedPixels'].iloc[i], img.shape)
            
            img = cv2.resize(img, (TRAIN_IMG_SIZE_HEIGHT, TRAIN_IMG_SIZE_WIDTH))
            mask = cv2.resize(mask, (TRAIN_IMG_SIZE_HEIGHT, TRAIN_IMG_SIZE_WIDTH))
            
            x_batch += [img]
            y_batch += [mask]
                                    
        x_batch = np.array(x_batch)
        y_batch = np.array(y_batch)

        yield x_batch, np.expand_dims(y_batch, -1)

In [29]:
def dice_coeff(y_true, y_pred):
    smooth = 1
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    return (2. * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)

def bce_dice_loss(y_true, y_pred):
    loss = 0.5 * binary_crossentropy(y_true, y_pred) - 2*dice_coeff(y_true, y_pred)
    return loss


In [30]:
base_model = Xception(weights='imagenet', input_shape=(TRAIN_IMG_SIZE_HEIGHT, TRAIN_IMG_SIZE_WIDTH, 3), include_top=False) #include_top=False excludes final FC layer
base_model.summary()


Instructions for updating:
Colocations handled automatically by placer.
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 128, 800, 3)  0                                            
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 63, 399, 32)  864         input_1[0][0]                    
__________________________________________________________________________________________________
block1_conv1_bn (BatchNormaliza (None, 63, 399, 32)  128         block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_conv1_act (Activation)   (None, 63, 399, 32)  0           block1_conv1_bn[0][0]            
_____________________________________

__________________________________________________________________________________________________
block5_sepconv1 (SeparableConv2 (None, 8, 50, 728)   536536      block5_sepconv1_act[0][0]        
__________________________________________________________________________________________________
block5_sepconv1_bn (BatchNormal (None, 8, 50, 728)   2912        block5_sepconv1[0][0]            
__________________________________________________________________________________________________
block5_sepconv2_act (Activation (None, 8, 50, 728)   0           block5_sepconv1_bn[0][0]         
__________________________________________________________________________________________________
block5_sepconv2 (SeparableConv2 (None, 8, 50, 728)   536536      block5_sepconv2_act[0][0]        
__________________________________________________________________________________________________
block5_sepconv2_bn (BatchNormal (None, 8, 50, 728)   2912        block5_sepconv2[0][0]            
__________

__________________________________________________________________________________________________
block9_sepconv1_act (Activation (None, 8, 50, 728)   0           add_7[0][0]                      
__________________________________________________________________________________________________
block9_sepconv1 (SeparableConv2 (None, 8, 50, 728)   536536      block9_sepconv1_act[0][0]        
__________________________________________________________________________________________________
block9_sepconv1_bn (BatchNormal (None, 8, 50, 728)   2912        block9_sepconv1[0][0]            
__________________________________________________________________________________________________
block9_sepconv2_act (Activation (None, 8, 50, 728)   0           block9_sepconv1_bn[0][0]         
__________________________________________________________________________________________________
block9_sepconv2 (SeparableConv2 (None, 8, 50, 728)   536536      block9_sepconv2_act[0][0]        
__________

add_11 (Add)                    (None, 8, 50, 728)   0           block12_sepconv3_bn[0][0]        
                                                                 add_10[0][0]                     
__________________________________________________________________________________________________
block13_sepconv1_act (Activatio (None, 8, 50, 728)   0           add_11[0][0]                     
__________________________________________________________________________________________________
block13_sepconv1 (SeparableConv (None, 8, 50, 728)   536536      block13_sepconv1_act[0][0]       
__________________________________________________________________________________________________
block13_sepconv1_bn (BatchNorma (None, 8, 50, 728)   2912        block13_sepconv1[0][0]           
__________________________________________________________________________________________________
block13_sepconv2_act (Activatio (None, 8, 50, 728)   0           block13_sepconv1_bn[0][0]        
__________